/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: 'us-east-1',
  aws_cognito_identity_pool_id: 'us-east-1:33f5d4c0-39c2-408e-a8df-c659435fde9c',
  aws_cognito_region: 'us-east-1',
  aws_user_pools_id: 'us-east-1_RE4BzsoNU',
  aws_user_pools_web_client_id: '4vjd7on2fa27vlikue28jlgjt6',
  oauth: {},
};

export default awsmobile;
